### PR TITLE
Update AzureTTS Service to support pitch

### PR DESCRIPTION
**Pull request by RawToast**
The same can be done for rate (-100 to 200), but as it's currently a string it breaks existing profiles 😿 I might instead look at adding more "steps" instead, so profiles don't get broken.

It's been a while since I wrote any Python 😆

### CODE REVIEW

**Comment by lucwastiaux** [comment]
Thanks for submitting, please give me a bit of time to test!

**Comment by RawToast** [comment]
> Thanks for submitting, please give me a bit of time to test!

No problem, I manually copy/pasted from my local add-ons. So it's possible I might have made a mistake... I've been using this locally for a few days and updated a hundreds of cards with it:

Screenshot 2020-09-27 at 13 43 01

[azure-f3a41e3d-32766f21-2596978f-e2fb5d50-ebceaec4.mp3.zip](https://github.com/AwesomeTTS/awesometts-anki-addon/files/5287739/azure-f3a41e3d-32766f21-2596978f-e2fb5d50-ebceaec4.mp3.zip)

**Comment by lucwastiaux** [comment]
Just curious, where did you get the +50/-50 range ? I don't see this documented here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=csharp#adjust-prosody

**Comment by RawToast** [comment]
Oh wow, they don't document it in the API, but it definitely works! If you go to the [features page](https://azure.microsoft.com/en-us/services/cognitive-services/text-to-speech/#features) you can try the service and adjust the pitch and rate with sliders. If you look at the ssml generated, it uses those values.

**Comment by lucwastiaux** [comment]
I'm thinking of implementing the various discrete pitch values that we can apparently use:
    x-low
    low
    medium
    high
    x-high
    default

would that also serve your purpose?

**Comment by lucwastiaux** [comment]
OK just did it that way and it works beautifully! so your change is essentially merged. Thank you for submitting this !

**Comment by RawToast** [comment]
Using the given discrete values is not as useful, the same goes for speed. I find `slow` is painfully slow and unnatural, whilst `default`/`normal` can be too fast at times. I tend to find myself using 0 through to -12, I can only presume `slow` is like -25 or something.

I like the variety of voices used by the Core decks, etc. Whilst with TTS, the Azure voice stands out as being natural -- unfortunately, it only has one voice. So I find myself create various profiles for the azure Japanese voice, with minor differences in pitch and speed. Then randomly apply these profiles to chunks of cards, this mimics having different "voice actors". 

Without the fine grades that are available in the service, this is not so useful 😢

**Comment by lucwastiaux** [comment]
In 1.24 the pitch uses discrete values. I understand this is not as useful to you, let me think of a way to smartly integrate continuous values. Closing this for now.

**Pull request closed without merging**
