### PR TITLE
support for naver papago (translate)

### PR DESCRIPTION
**Pull request by gsittyz**
The current code doesn't work any longer, so I wrote a new script for Naver Papago (Translate) with some new languages.

### CODE REVIEW

**Comment by gsittyz** [comment]
This request may solve #117 .

**Comment by lucwastiaux** [comment]
Thanks for submitting this, let me take a look !

**Comment by lucwastiaux** [comment]
Thanks a lot for submitting !

**Comment by lovac42** [comment]
Thanks!  Just a suggestion, the HMAC_KEY has changed several times this quarter already. Perhaps allow the user to change it on-the-fly like an optional API key? That will save the hassle of updating this every few weeks.

**Comment by lucwastiaux** [comment]
@lovac42 thanks for the suggestion. Note that I have automated tests in place so I should be able to spot when it starts breaking

**Pull request merged**
