### PR TITLE
Fix Naver Service

### PR DESCRIPTION
**Pull request by Shadowlauch**
This fixes the issues introduced by the new Naver API. Most of the groundwork was done by @sjhuang26 #61.

I don't use python much, so if there is anything that looks strange, please let me know.

### CODE REVIEW

**Comment by daniesteban** [comment]
I don't know much python either, but I tested the committed file in my computer and it works like a charm, 150 audio sentences added fast and clean. I hope it can be merged soon for everyone enjoy, naver outweighs the others translation platforms like google translate.
Thank you for the effort guys.

**Comment by daniesteban** [comment]
I'm actively using the fix and the only problem I get is that it fails when the sentence has double quotes symbol (")

**Comment by fishstik** [comment]
Could you describe how you used this fix? I copied over the changed file and overwrote naver.py but I'm getting this error:
image
(I added AA to the desc string to make sure it was picking up my changes).

**Comment by daniesteban** [comment]
I simply rename original naver.py file and put [the modified one](https://raw.githubusercontent.com/AwesomeTTS/awesometts-anki-addon/a2d2cb125aaab12a4bd402642ffbae2f8898216f/awesometts/service/naver.py) instead.
Path to file: /home/[username]/.local/share/Anki2/addons/awesometts/service/naver.py

I'm using anki Version 2.0.47 on Linux and translate only English sentences.

**Comment by fishstik** [comment]
I reverted back to Anki 2.0.52 on Windows and can confirm it works for Japanese passages.

**Comment by lovac42** [comment]
https://github.com/Shadowlauch/awesometts-anki-addon/blob/master-2.0/awesometts/service/base.py#L549

For 2.1, on base.py, somewhere around L544 was changed to str(val). Changing this to just val fixed the string not bytes issue for naver, but failed for google.
```
    )(
        str(val),
        safe='',
    ),
```

**Comment by cliffspradlin** [comment]
The current version of the papago website has been updated to use the 'kyuri' voice for female and 'jinho' for male. These sound much clearer and better to me than the 'mijin' voice that this patch still uses.

**Comment by Shadowlauch** [comment]
@cliffspradlin I will have a look at that later

**Comment by Shadowlauch** [comment]
@cliffspradlin could you post the url to that link. I tried the different speaker and they sound the same to me.

**Comment by M-Azuma** [comment]
eescueta's version for Japanese is about 2 times slower than the website's one, which is too slow for me. I have to use the website instead.

I tried to change speed values but with no luck and even finally got 400 bad requests. I think I am temporarily blocked.

**Comment by cliffspradlin** [comment]
> @cliffspradlin could you post the url to that link. I tried the different speaker and they sound the same to me.

Sure. Example: 부끄러워

Hopefully these URLs stay active:
kyuri: https://papago.naver.com/apis/tts/c_lt_3174-nvoice_kyuri_1.13.15_021991945bda075e30f77ed1a381b79e-1589526825804

mijin: https://papago.naver.com/apis/tts/c_lt_8464-nvoice_mijin_1.13.15_480389d5d0d83e4d0b8efba18e26841c-1589527184616

**Comment by lucwastiaux** [comment]
already fixed in #79 , let me know whether additional changes are required

**Pull request closed without merging**
