### PR TITLE
AWS Polly support

### PR DESCRIPTION
**Pull request by artem7902**
I just add AWS Polly support, its require boto3 library and other dependencies so i create folder for this. Also I add dependent second combo box. Please let me know if I need to change something for apply this pull request.

### CODE REVIEW

**Comment by artem7902** [comment]
Travis failed because Polly needs AWS credentials. I can't fix it because Travis not allowed to insert encrypted variables to pull requests.

**Comment by arthurdouillard** [comment]
Hello,

Is there any update on this addon?

Thanks,

**Comment by lucwastiaux** [comment]
hi @artem7902 , how did you package the files in the "dependencies/" folder ? Also, what are the advantages of AWS Polly compared to competitors like Google Cloud TTS or Azure Cognitive Services ?
thank you.

**Comment by evandrocoan** [comment]
I suggest removing the `pip install` from .travis and bundle the module in a git submodule. Then, when exporting it to Anki Addons page, we just zip this repository after a `git clone --recursive` and removing the `.git` directory.

**Comment by lucwastiaux** [comment]
The git sub module idea is interesting but it does make the Travis build more complicated. Right now the Travis build is super simple, it even installs anki modules via pip.
Is there a rest-only api for AWS polly?

**Comment by lucwastiaux** [comment]
Going to close this temporarily, need think some more about how this can be integrated.

**Comment by Marakai** [comment]
Hi! I didn't want to open a new ticket but I'm interested in the AWS support aspect. Coming in this "sideways" I'm not quite clear what the issues would be - for example why the fork/PR has this whole dependencies directory instead of adding them via pip: just running pip install doesn't (yet) need credentials no more than you need an Azure API key.

I might try this from a different approach, trying to make it compact. However, the issue would remain that AWS does not simply use some API key, instead you're using IAM credentials, requiring a slight change in the UI of the AwesomeTTS Anki window.

Maybe I'm just missing something?

**Comment by barolo** [comment]
What happened here? Poly neural has some of the best voices imho, and has quite high free tier caps

**Comment by lucwastiaux** [comment]
@Marakai @barolo the problem is around how we manage the massive number of files that we'll have to import to have this boto3 library available standalone with awesometts. How do we do updates, etc. I'm not sure how it's going to be done, maybe there's an elegant way. The original submitter of this PR didn't include any details about how he packaged the files. Packaging one time is not sufficient, we'll have to worry about how we update this boto3 module when necessary.

**Pull request closed without merging**
