### PR TITLE
Support for Anki 2.1.20 & Add Google Cloud Text-to-Speech

### PR DESCRIPTION
**Pull request by kelciour**
It contains all the changes from the unofficial version with Google Cloud Text-to-Speech support - https://ankiweb.net/shared/info/814349176

It's unlikely it'll be updated anytime soon, at least I'm no longer interested to do it except maybe updating the list of available voices sometime later.

I think, it fixes the following issues:

- Fixes AwesomeTTS/awesometts-anki-addon#29
- Fixes AwesomeTTS/awesometts-anki-addon#32
- Fixes AwesomeTTS/awesometts-anki-addon#38
- Fixes AwesomeTTS/awesometts-anki-addon#39
- Fixes AwesomeTTS/awesometts-anki-addon#54
- Fixes AwesomeTTS/awesometts-anki-addon#72
- Fixes AwesomeTTS/awesometts-anki-addon#84
- Fixes AwesomeTTS/awesometts-anki-addon#85
- Fixes AwesomeTTS/awesometts-anki-addon#86

### CODE REVIEW

**Comment by lucwastiaux** [comment]
I have tested this build and it's working for me. going to merge it.

**Comment by kelciour** [comment]
This is great!

**Comment by lucwastiaux** [comment]
thanks for doing this, can I confirm that you're the author who submitted this addon ? https://ankiweb.net/shared/info/814349176
my plan is to get the regular continuous build going for this project, merge all the outstanding pull requests and forks, then make an updated release. Though at this point, the "AwesomeTTS (Google Cloud Text-to-Speech) [unofficial]" addon is probably the default AwesomeTTS one.

**Comment by kelciour** [comment]
Yes, it's me.

**Comment by lucwastiaux** [comment]
Thank you, and what's your plan going forward with AwesomeTTS, are you going to make additional changes to your fork ? I'd be more than happy to help review, test and merge if that's the case. If on the other hand you're done with working on the addon for a while, what's your thought about steering new users to the new addon page (https://ankiweb.net/shared/info/1436550454) ? 

We owe you a lot for your changes on google cloud TTS so I welcome your input. My thought is that we should present a single addon page to users of Anki, to avoid any confusion.

**Comment by kelciour** [comment]
I've updated the add-on's page and added a link to the new add-on.

Maybe I'll add a few more commits and send a pull request with the changes,
but essentially I'm not very interested and aside from updating Google
Cloud Text-to-Speech voices once in a while, it's unlikely I'll be
interested to keep my fork up-to-date or do anything else anytime soon.


вт, 16 июн. 2020 г. в 11:18, LucW <notifications@github.com>:

**Pull request merged**
