### PR TITLE
Fix issue #36: Correctly preview cloze deleted text

### LINKED ISSUE #36: Cloze deleted text not getting substituted properly
Steps to reproduce:

1. Open Tools > AwesomeTTS... > "Text" tab
2. In "Handling text from a **Note** Field" section, for option "For a braced cloze marker", choose "replace w/ deleted text"
3. Click OK to save settings.
4. Open a card with Cloze deletion in note editor 
5. Highlight text with a braced close marker (such as "Hello, {{c1::world}}!").
6. Open AwesomeTTS by clicking the AwesomeTTS icon.

**Expected behavior:**
Preview field shows "Hello, world!"

**Actual behavior:**
Preview field shows "Hello, c!"

Awesome TTS version: master (2018-02-21)
Anki version: 2.1.0beta29
Qt version: Qt 5.10.0 PyQt 5.9.2

### PR DESCRIPTION
**Pull request by hjorthjort**
I found that this fixes the issue on my setup.

### CODE REVIEW

**Comment by krassowski** [comment]
@felixraumann, can I merge this as well as #34?

**Comment by hjorthjort** [comment]
If that's the case, you shouldn't merge yet. There were some more matches in the file, which would all need to be shifted.

**Comment by krassowski** [comment]
Indeed. I think that we can create tests for the regex handling so if Anki
changes it again, we will know sooner.

**Comment by hjorthjort** [comment]
Do you have any documentation/pointers on how your testing works?

**Comment by krassowski** [comment]
It uses pytest ([documentation](https://docs.pytest.org/en/latest/)). To install pytest use:
```bash
python3.6 -m pip install pytest
```

All what is needed is to add a new python file starting with `test_` in `tests` directory (e.g. `tests/test_text.py`) and add a function, also starting with `test_`, e.g.

```python
def test_cloze_rules():
    deleter_rule = Sanitizer._rule_clozes_braced.deleter
    assert CLOZE_BRACED.sub(deleter_rule, '{{c1::some text}}') == 'some text'
    assert CLOZE_BRACED.sub(deleter_rule '{{c1::}}') == '...'
```

Then to check if it works run `bash tools/test.sh` from the root of the repository (assuming Linux/Mac) or manually check if you have all required tools, install the latest Anki version in predefined location as the `tools/test.sh` script would, and run tests: `python3.6 -m pytest tests`.

**Comment by hjorthjort** [comment]
I shifted the other groups clozure groups as well.

**Comment by hjorthjort** [comment]
Thanks for the pointers. Will give it a go tomorrow (Japan timezone).

**Comment by hjorthjort** [comment]
I'm having some issues getting the testing framework to run. Getting "core dumped" errors when running tests.sh or `python3.6 -m pytests tests/`. Also, errors pop up further down the call stack from `import anki` in  statements because the anki module can't be found, for example. I'm not sure I have the time to dive too deep for such a small fix.

I reversed the changes to the rendered  clozes as well. Since I don't really have a running setup, I could only explore how anki implements this by reading code, and again, I'm a bit strapped for time.

Thanks for your help!

**Pull request merged**
